CREATE TABLE `incidents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fileKey` varchar(512),
	`fileUrl` varchar(1024),
	`fileMimeType` varchar(64),
	`occurredAt` varchar(128),
	`location` varchar(256),
	`subjectInitials` varchar(64),
	`summaryWhat` text,
	`summaryCause` text,
	`summaryResult` text,
	`impactLevel` enum('0','1','2','3a','3b','4','5') DEFAULT '0',
	`urgency` enum('High','Medium','Low') DEFAULT 'Low',
	`importance` enum('High','Medium','Low') DEFAULT 'Low',
	`locationTag` enum('facility','visit') DEFAULT 'facility',
	`preventionActions` text,
	`status` enum('draft','confirmed') NOT NULL DEFAULT 'draft',
	`isUrgentAlerted` boolean DEFAULT false,
	`createdByUserId` int,
	`confirmedByUserId` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`confirmedAt` timestamp,
	CONSTRAINT `incidents_id` PRIMARY KEY(`id`)
);
