import { useRef, useState } from "react";
import { ArchiveRestore, Download, HardDrive, ShieldAlert, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { downloadLocalBackup, restoreLocalBackup } from "@/lib/localBackup";
import { toast } from "sonner";

export default function BackupPage() {
  const inputRef = useRef<HTMLInputElement>(null);
  const [isBusy, setIsBusy] = useState(false);
  const exportBackup = async () => { setIsBusy(true); try { await downloadLocalBackup(); toast.success("バックアップZIPをダウンロードしました。"); } catch { toast.error("バックアップの作成に失敗しました。"); } finally { setIsBusy(false); } };
  const importBackup = async (file?: File) => { if (!file) return; if (!window.confirm("現在の端末内データをバックアップ内容で置き換えます。よろしいですか？")) return; setIsBusy(true); try { const result = await restoreLocalBackup(file, "replace"); toast.success(`${result.reports}件の報告書と${result.attachments}件の添付を復元しました。`); } catch (error) { toast.error(error instanceof Error ? error.message : "復元に失敗しました。"); } finally { setIsBusy(false); if (inputRef.current) inputRef.current.value = ""; } };
  return <div className="max-w-3xl mx-auto space-y-5"><div><p className="text-sm font-medium text-teal-700">データ保全</p><h1 className="mt-1 text-2xl font-bold">バックアップ・復元</h1><p className="mt-2 text-sm text-muted-foreground">報告書・添付画像・PDFを、端末内のZIPファイルへ書き出し、同じ形式で復元できます。</p></div><Card className="border-amber-200 bg-amber-50/40 shadow-none"><CardContent className="pt-5 flex gap-3"><ShieldAlert className="h-5 w-5 text-amber-700 shrink-0 mt-0.5" /><div className="text-sm leading-6 text-amber-900"><p className="font-medium">端末内データは自動同期されません。</p><p>ブラウザのサイトデータ削除、端末の初期化・紛失・故障で消える可能性があります。定期的にZIPバックアップを作成し、暗号化済みの外部媒体または施設の安全な保管領域へ保存してください。</p></div></CardContent></Card><div className="grid md:grid-cols-2 gap-4"><Card className="shadow-none"><CardHeader><CardTitle className="text-base flex gap-2 items-center"><Download className="h-4 w-4 text-teal-700" />バックアップを書き出す</CardTitle></CardHeader><CardContent className="space-y-4 text-sm text-muted-foreground"><p>この端末内の全報告書・添付ファイルをひとつのZIPにまとめます。ファイルはネットワークへ送信されません。</p><Button onClick={() => void exportBackup()} disabled={isBusy} className="w-full bg-teal-700 hover:bg-teal-800"><HardDrive className="h-4 w-4 mr-2" />{isBusy ? "処理中..." : "バックアップZIPを作成"}</Button></CardContent></Card><Card className="shadow-none"><CardHeader><CardTitle className="text-base flex gap-2 items-center"><ArchiveRestore className="h-4 w-4 text-indigo-700" />バックアップから復元</CardTitle></CardHeader><CardContent className="space-y-4 text-sm text-muted-foreground"><p>作成済みのバックアップZIPを選ぶと、現在の端末内データを置き換えて復元します。</p><input ref={inputRef} type="file" accept=".zip,application/zip" className="hidden" onChange={(event) => void importBackup(event.target.files?.[0])} /><Button variant="outline" onClick={() => inputRef.current?.click()} disabled={isBusy} className="w-full"><Upload className="h-4 w-4 mr-2" />バックアップZIPを選択</Button></CardContent></Card></div></div>;
}
