import { useEffect, useRef, useState } from "react";
import { useLocation, useParams } from "wouter";
import { ArrowLeft, CheckCircle2, Download, Paperclip, Plus, Save, Trash2, Upload } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { addLocalAttachments, deleteLocalAttachment, deleteLocalReport, getLocalReport, listLocalAttachments, saveLocalReport, type LocalAttachment, type LocalReport } from "@/lib/localDb";
import { downloadElementAsPdf } from "@/lib/localPdf";
import { toast } from "sonner";

const impactLevels = ["0", "1", "2", "3a", "3b", "4", "5"] as const;
const fishboneKeys = ["人", "手順", "機械・設備", "環境", "管理"];

function AttachmentRow({ attachment, onDelete }: { attachment: LocalAttachment; onDelete: () => void }) {
  const [url, setUrl] = useState("");
  useEffect(() => { const next = URL.createObjectURL(attachment.blob); setUrl(next); return () => URL.revokeObjectURL(next); }, [attachment.blob]);
  const isImage = attachment.type.startsWith("image/");
  return <div className="rounded-lg border p-3 bg-muted/20"><div className="flex gap-3 items-center justify-between"><div className="min-w-0 flex-1"><p className="text-sm font-medium truncate">{attachment.name}</p><p className="text-xs text-muted-foreground mt-1">{Math.ceil(attachment.size / 1024)} KB ・ 端末内保存</p></div><div className="flex gap-2"><a href={url} download={attachment.name}><Button size="sm" variant="outline">開く</Button></a><Button size="sm" variant="ghost" onClick={onDelete} className="text-destructive"><Trash2 className="h-4 w-4" /></Button></div></div>{isImage && <img src={url} alt={attachment.name} className="mt-3 rounded-md max-h-64 object-contain bg-white" />}</div>;
}

export default function IncidentReviewPage() {
  const { id = "" } = useParams<{ id: string }>();
  const [, setLocation] = useLocation();
  const pdfRef = useRef<HTMLDivElement>(null);
  const [report, setReport] = useState<LocalReport | null>(null);
  const [attachments, setAttachments] = useState<LocalAttachment[]>([]);
  const [newReportedAction, setNewReportedAction] = useState("");
  const [newSuggestedAction, setNewSuggestedAction] = useState("");
  const [isSaving, setIsSaving] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);

  const reload = async () => { const next = await getLocalReport(id); if (!next) { setLocation("/incidents"); return; } setReport(next); setAttachments(await listLocalAttachments(id)); };
  useEffect(() => { void reload(); }, [id]);
  if (!report) return <div className="py-16 text-center text-sm text-muted-foreground">報告書を読み込み中です...</div>;
  const update = <K extends keyof LocalReport>(key: K, value: LocalReport[K]) => setReport((current) => current ? { ...current, [key]: value } : current);
  const save = async (status = report.status) => { setIsSaving(true); try { const next = await saveLocalReport({ ...report, status }); setReport(next); toast.success(status === "confirmed" ? "報告書を確定しました。" : "変更を端末内に保存しました。"); } catch { toast.error("保存に失敗しました。"); } finally { setIsSaving(false); } };
  const attach = async (files: File[]) => { try { await addLocalAttachments(report.id, files); await reload(); toast.success("添付を端末内へ保存しました。"); } catch { toast.error("添付の保存に失敗しました。"); } };
  const remove = async () => { if (!window.confirm("この報告書とすべての添付を端末から削除します。よろしいですか？")) return; await deleteLocalReport(report.id); toast.success("削除しました。"); setLocation("/incidents"); };
  const downloadPdf = async () => { if (!pdfRef.current) return; setIsDownloading(true); try { await downloadElementAsPdf(pdfRef.current, `report-${report.id.slice(0, 8)}.pdf`); toast.success("PDFを端末へ保存しました。"); } catch { toast.error("PDF出力に失敗しました。"); } finally { setIsDownloading(false); } };
  const appendAction = (field: "reportedActions" | "aiSuggestedActions", value: string, clear: () => void) => { if (!value.trim()) return; update(field, [...report[field], value.trim()]); clear(); };

  return <div className="max-w-5xl mx-auto space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><Button variant="ghost" className="gap-2" onClick={() => setLocation("/incidents")}><ArrowLeft className="h-4 w-4" />一覧へ戻る</Button><div className="flex flex-wrap gap-2"><Badge variant={report.reportType === "accident" ? "destructive" : "secondary"}>{report.reportType === "accident" ? "アクシデント" : "インシデント"}</Badge><Badge variant="outline">{report.status === "confirmed" ? "確定済み" : "下書き"}</Badge><Button variant="outline" onClick={() => void downloadPdf()} disabled={isDownloading} className="gap-2"><Download className="h-4 w-4" />{isDownloading ? "作成中..." : "PDF保存"}</Button><Button variant="destructive" size="icon" onClick={() => void remove()} aria-label="削除"><Trash2 className="h-4 w-4" /></Button></div></div>
    <div ref={pdfRef} className="bg-white p-1 space-y-5"><Card className="shadow-none"><CardHeader><CardTitle className="text-xl">{report.reportType === "accident" ? "アクシデント（事故報告書）" : "インシデント（ヒヤリハット）"}</CardTitle><p className="text-xs text-muted-foreground">端末内で編集・保存されています。外部サーバーへの送信はありません。</p></CardHeader><CardContent className="grid gap-5"><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div className="space-y-2"><Label>報告種別</Label><Select value={report.reportType} onValueChange={(value) => update("reportType", value as LocalReport["reportType"])}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="incident">インシデント</SelectItem><SelectItem value="accident">アクシデント</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>発生日時</Label><Input type="datetime-local" value={report.occurredAt} onChange={(event) => update("occurredAt", event.target.value)} /></div><div className="space-y-2"><Label>発生場所</Label><Input value={report.location} onChange={(event) => update("location", event.target.value)} /></div><div className="space-y-2"><Label>対象者（イニシャル等）</Label><Input value={report.subjectInitials} onChange={(event) => update("subjectInitials", event.target.value)} /></div></div><div className="space-y-2"><Label>事象概要（何が起きたか）</Label><Textarea className="min-h-24" value={report.summaryWhat} onChange={(event) => update("summaryWhat", event.target.value)} /></div><div className="grid md:grid-cols-2 gap-4"><div className="space-y-2"><Label>想定される要因</Label><Textarea value={report.summaryCause} onChange={(event) => update("summaryCause", event.target.value)} /></div><div className="space-y-2"><Label>結果・対応状況</Label><Textarea value={report.summaryResult} onChange={(event) => update("summaryResult", event.target.value)} /></div></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><div className="space-y-2"><Label>影響度</Label><Select value={report.impactLevel} onValueChange={(value) => update("impactLevel", value as LocalReport["impactLevel"])}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{impactLevels.map((level) => <SelectItem key={level} value={level}>レベル {level}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>緊急対応性</Label><Select value={report.urgency} onValueChange={(value) => update("urgency", value as LocalReport["urgency"])}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["Low", "Medium", "High"].map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>重要度</Label><Select value={report.importance} onValueChange={(value) => update("importance", value as LocalReport["importance"])}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{["Low", "Medium", "High"].map((value) => <SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></div></div></CardContent></Card>
      <Card className="shadow-none"><CardHeader><CardTitle className="text-base">対策・再発防止策</CardTitle></CardHeader><CardContent className="grid md:grid-cols-2 gap-5"><ActionEditor title="報告書に記載された対策" actions={report.reportedActions} value={newReportedAction} onValueChange={setNewReportedAction} onAdd={() => appendAction("reportedActions", newReportedAction, () => setNewReportedAction(""))} onRemove={(index) => update("reportedActions", report.reportedActions.filter((_, i) => i !== index))} /><ActionEditor title="再発防止策（手入力）" actions={report.aiSuggestedActions} value={newSuggestedAction} onValueChange={setNewSuggestedAction} onAdd={() => appendAction("aiSuggestedActions", newSuggestedAction, () => setNewSuggestedAction(""))} onRemove={(index) => update("aiSuggestedActions", report.aiSuggestedActions.filter((_, i) => i !== index))} /></CardContent></Card>
      <Card className="shadow-none"><CardHeader><CardTitle className="text-base">フィッシュボーン要因整理</CardTitle></CardHeader><CardContent className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{fishboneKeys.map((key) => <div key={key} className="space-y-2"><Label>{key}</Label><Textarea value={(report.fishbone[key] ?? []).join("\n")} onChange={(event) => update("fishbone", { ...report.fishbone, [key]: event.target.value.split("\n").map((item) => item.trim()).filter(Boolean) })} placeholder="1行に1項目" /></div>)}</CardContent></Card>
      <Card className="shadow-none"><CardHeader><CardTitle className="text-base">添付ファイル（端末内保存）</CardTitle></CardHeader><CardContent className="space-y-3"><Label className="inline-flex"><Input type="file" accept="image/*,.pdf,application/pdf" multiple className="sr-only" onChange={(event) => void attach(Array.from(event.target.files ?? []))} /><Button variant="outline" asChild><span><Upload className="h-4 w-4 mr-2" />添付を追加</span></Button></Label>{attachments.length === 0 ? <p className="text-sm text-muted-foreground">添付はありません。</p> : <div className="grid lg:grid-cols-2 gap-3">{attachments.map((attachment) => <AttachmentRow key={attachment.id} attachment={attachment} onDelete={() => void deleteLocalAttachment(attachment.id).then(reload)} />)}</div>}</CardContent></Card>
    </div><div className="flex flex-col-reverse sm:flex-row justify-end gap-3"><Button variant="outline" disabled={isSaving} onClick={() => void save()} className="gap-2"><Save className="h-4 w-4" />下書きを保存</Button><Button disabled={isSaving} onClick={() => void save("confirmed")} className="bg-teal-700 hover:bg-teal-800 gap-2"><CheckCircle2 className="h-4 w-4" />確定して保存</Button></div>
  </div>;
}

function ActionEditor({ title, actions, value, onValueChange, onAdd, onRemove }: { title: string; actions: string[]; value: string; onValueChange: (value: string) => void; onAdd: () => void; onRemove: (index: number) => void }) {
  return <div className="space-y-2"><Label>{title}</Label><div className="space-y-2">{actions.map((action, index) => <div key={`${action}-${index}`} className="flex gap-2 text-sm bg-muted/40 p-2 rounded-md"><span className="flex-1">{action}</span><button type="button" onClick={() => onRemove(index)} className="text-destructive"><Trash2 className="h-4 w-4" /></button></div>)}</div><div className="flex gap-2"><Input value={value} onChange={(event) => onValueChange(event.target.value)} placeholder="対策を入力" onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); onAdd(); } }} /><Button type="button" size="icon" variant="outline" onClick={onAdd}><Plus className="h-4 w-4" /></Button></div></div>;
}
