import { useEffect, useRef, useState } from "react";
import { Download, FileBarChart2, MapPin, Tag, TrendingUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { downloadElementAsPdf } from "@/lib/localPdf";
import { getMonthlyLocalReport, type MonthlyGroupStats, type MonthlyLocalReport } from "@/lib/localDb";
import { toast } from "sonner";

const levels = ["0", "1", "2", "3a", "3b", "4", "5"];
const timeOrder = ["深夜(0-5時)", "早朝(6-11時)", "日中(12-17時)", "夕方夜間(18-23時)"];
function Bar({ label, count, max, tone = "bg-teal-500" }: { label: string; count: number; max: number; tone?: string }) { return <div className="flex items-center gap-2 text-xs"><span className="w-24 truncate text-muted-foreground">{label}</span><span className="h-2 flex-1 overflow-hidden rounded-full bg-muted"><span className={`block h-full rounded-full ${tone}`} style={{ width: `${max ? Math.max(4, Math.round((count / max) * 100)) : 0}%` }} /></span><span className="w-7 text-right font-semibold">{count}</span></div>; }
function GroupPanel({ title, group, accident = false }: { title: string; group: MonthlyGroupStats; accident?: boolean }) { const maxLevel = Math.max(...levels.map((level) => group.byImpactLevel[level] ?? 0), 1); const maxLocation = group.topLocations[0]?.count ?? 1; const maxTime = Math.max(...timeOrder.map((time) => group.timeBlocks[time] ?? 0), 1); const tone = accident ? "bg-orange-500" : "bg-teal-500"; return <Card className={`shadow-none border-l-4 ${accident ? "border-l-orange-500" : "border-l-teal-500"}`}><CardHeader className="py-4"><div className="flex justify-between items-center"><CardTitle className="text-base">{title}</CardTitle><Badge className={accident ? "bg-orange-100 text-orange-800" : "bg-teal-100 text-teal-800"}>{group.total}件</Badge></div></CardHeader><CardContent className="space-y-5">{group.total === 0 ? <p className="py-6 text-center text-sm text-muted-foreground">該当月の確定済み報告書はありません。</p> : <><section><p className="mb-2 flex items-center gap-1.5 text-xs font-semibold"><TrendingUp className="h-3.5 w-3.5" />影響度レベル分布</p><div className="space-y-1.5">{levels.filter((level) => group.byImpactLevel[level]).map((level) => <Bar key={level} label={`Lv${level}`} count={group.byImpactLevel[level]} max={maxLevel} tone={tone} />)}</div></section><section><p className="mb-2 flex items-center gap-1.5 text-xs font-semibold"><MapPin className="h-3.5 w-3.5" />発生場所 TOP5</p><div className="space-y-1.5">{group.topLocations.map((item) => <Bar key={item.name} label={item.name} count={item.count} max={maxLocation} tone="bg-blue-500" />)}</div></section><section><p className="mb-2 text-xs font-semibold">時間帯別発生状況</p><div className="space-y-1.5">{timeOrder.map((time) => <Bar key={time} label={time} count={group.timeBlocks[time] ?? 0} max={maxTime} tone="bg-violet-500" />)}</div></section><section><p className="mb-2 flex items-center gap-1.5 text-xs font-semibold"><Tag className="h-3.5 w-3.5" />頻出キーワード</p><div className="flex flex-wrap gap-1.5">{group.topKeywords.length ? group.topKeywords.map((item) => <Badge key={item.keyword} variant="secondary">{item.keyword} {item.count}件</Badge>) : <span className="text-xs text-muted-foreground">検出されたキーワードはありません。</span>}</div></section></>}</CardContent></Card>; }

export default function MonthlyReportPage() {
  const current = new Date(); const [year, setYear] = useState(current.getFullYear()); const [month, setMonth] = useState(current.getMonth() + 1); const [data, setData] = useState<MonthlyLocalReport | null>(null); const [busy, setBusy] = useState(false); const pdfRef = useRef<HTMLDivElement>(null);
  useEffect(() => { void getMonthlyLocalReport(year, month).then(setData); }, [year, month]);
  const exportPdf = async () => { if (!pdfRef.current) return; setBusy(true); try { await downloadElementAsPdf(pdfRef.current, `monthly-report-${year}-${String(month).padStart(2, "0")}.pdf`); toast.success("月次レポートをPDFとして端末へ保存しました。"); } catch { toast.error("PDF保存に失敗しました。"); } finally { setBusy(false); } };
  return <div className="max-w-6xl mx-auto space-y-5"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm text-teal-700 font-medium">端末内データのみで集計</p><h1 className="text-2xl font-bold mt-1">月次レポート</h1><p className="text-sm text-muted-foreground mt-2">確定済みのローカル報告書を、インシデント・アクシデント別に分析します。</p></div><Button onClick={() => void exportPdf()} disabled={!data || busy} className="bg-teal-700 hover:bg-teal-800 gap-2"><Download className="h-4 w-4" />{busy ? "PDF作成中..." : "A4 PDFを保存"}</Button></div><Card className="shadow-none"><CardContent className="p-4 flex items-center gap-3"><span className="text-sm text-muted-foreground">対象月</span><Select value={String(year)} onValueChange={(value) => setYear(Number(value))}><SelectTrigger className="w-28"><SelectValue /></SelectTrigger><SelectContent>{Array.from({ length: 5 }, (_, index) => current.getFullYear() - index).map((value) => <SelectItem key={value} value={String(value)}>{value}年</SelectItem>)}</SelectContent></Select><Select value={String(month)} onValueChange={(value) => setMonth(Number(value))}><SelectTrigger className="w-24"><SelectValue /></SelectTrigger><SelectContent>{Array.from({ length: 12 }, (_, index) => index + 1).map((value) => <SelectItem key={value} value={String(value)}>{value}月</SelectItem>)}</SelectContent></Select>{data && <Badge variant="outline">確定済み合計 {data.totalAll}件</Badge>}</CardContent></Card><div ref={pdfRef} className="bg-white p-1"><div className="rounded-xl bg-teal-700 text-white px-5 py-4 mb-4 flex justify-between"><div><h2 className="font-bold">{year}年{month}月 インシデント・アクシデント月次レポート</h2><p className="text-xs text-teal-100 mt-1">この端末内の確定済み報告書から作成</p></div><div className="text-right"><p className="text-xs text-teal-100">合計件数</p><p className="text-xl font-bold">{data?.totalAll ?? 0}件</p></div></div>{data ? <div className="grid md:grid-cols-2 gap-4"><GroupPanel title="インシデント（ヒヤリハット）" group={data.incident} /><GroupPanel title="アクシデント（事故報告書）" group={data.accident} accident /></div> : <Card><CardContent className="py-16 text-center text-sm text-muted-foreground">集計中...</CardContent></Card>}</div></div>;
}
